---
replicaCount: 1

image:
  repository: amazon/dynamodb-local
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClassName: manual
  accessMode: ReadWriteOnce
  size: 1Mi